# This is a basic workflow to help you get started with Actions

name: after_merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
   Today: ""
   Yestorday: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    environment: npm

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '--test-001--'
          echo '${{ toJSON(github) }}'

      - uses: actions/checkout@v2
 
      - name: Get environment cache
        id: cache-environment
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/bin/ninja
            /usr/local/Cellar/node
            /usr/local/bin/node
            /usr/local/Cellar/emscripten
            /usr/local/bin/emscripten
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/Cellar/depsync
            /usr/local/bin/depsync
            /usr/local/Cellar/gcovr
            /usr/local/bin/gcovr
          key: libpag1-environment-20220208 
      - name: Test
        run: |
          chmod +x test.sh
          ./test.sh          
