# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: cache-third_party
        id: cache-third_party
        uses: actions/cache@v2
        with:
          path: |
           /usr/local/Cellar/ninja
           /usr/local/bin/ninja
           /usr/local/Cellar/node
           /usr/local/bin/node
           /usr/local/Cellar/emscripten
           /usr/local/bin/emscripten
           /usr/local/Cellar/yasm
           /usr/local/bin/yasm
           /usr/local/Cellar/depsync
           /usr/local/bin/depsync
           /dev/null
          key: yasm-008
      - name: pull third-party dependencies   
        if: steps.cache-third_party.outputs.cache-hit == 'true'
        run: |
          brew link emscripten
          chmod +x test.sh
          ./test.sh
          
      - name: pull third-party dependencies1   
        if: steps.cache-third_party.outputs.cache-hit != 'true'
        run: |
          chmod +x test.sh
          ./test.sh
        
