# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.0
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  push:
  schedule:
    - cron: '16 8 * * *'

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest
    permissions:
   # Required for all workflows
     security-events: write

  # Only required for workflows in private repositories
     actions: read
     contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp']
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'

