# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Dump GitHub context
        id: github_context_step
      - name: git branch 
        run: |
          git branch
          tar cvfa result.tar.zst result
      - name: libpag001
        id: Test01
        uses: actions/cache@v2
        with:
          path: result.tar.zst
          key: result-${{ hashFiles('result.tar.zst') }}
      - name: pull third-party dependencies1   
        if: steps.Test01.outputs.cache-hit != 'true'
        run: |
          echo "----------found-------"
      - name: pull third-party dependencies2
        if: steps.Test01.outputs.cache-hit == 'true'
        run: |
          chmod +x test2.sh
          ./test2.sh
        
